### ISSUE TITLE
when run ./init.sh    AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by maruitao** [unsky/RetinaNet#14]
ENV :  python3.5.5  cuda8.0  mxnet0.9.5  GTX1080Ti * 2

I run ./init.sh  after finished dependency  Cython mxnet_cu80==0.9.5  , get Errors:

Traceback (most recent call last):
  File "setup_linux.py", line 56, in <module>
    CUDA = locate_cuda()
  File "setup_linux.py", line 51, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

What should I do ?

**Comment by maruitao** [comment]
This problems is due to the version of python,  Use python2.7 is OK
