### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by wujiachen987** [unsky/RetinaNet#5]
I successful run the train.py ,but I can't run the test.py.
Traceback (most recent call last):
  File "/home/zzz/pycharm-community-2017.2.3/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/zzz/pycharm-community-2017.2.3/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/zzz/RetinaNet/retinanet/test.py", line 56, in <module>
    main()
  File "/home/zzz/RetinaNet/retinanet/test.py", line 53, in main
    args.vis, args.ignore_cache, args.shuffle, config.TEST.HAS_RPN, config.dataset.proposal, args.thresh, logger=logger, output_path=final_output_path)
  File "/home/zzz/RetinaNet/retinanet/function/test_rcnn.py", line 37, in test_rcnn
    imdb = eval(dataset)(image_set, root_path, dataset_path, result_path=output_path)
  File "/home/zzz/RetinaNet/retinanet/../lib/dataset/kitti.py", line 38, in __init__
    self._image_index = self._load_image_set_index()
  File "/home/zzz/RetinaNet/retinanet/../lib/dataset/kitti.py", line 69, in _load_image_set_index
    'Path does not exist: {}'.format(image_set_file)
AssertionError: Path does not exist: ../data/kitti/ImageSets/imageset.txt

I downloaded the datasets which you support,but it haven't imagesets ,how can i do?

Thanks. @unsky

**Comment by ChienLiu** [comment]
Can you give a brief explanation of the training steps? 
Because the author's description is not very detailed, the Internet can not find other discussions.
Sorry to bother you.

**Comment by wujiachen987** [comment]
@ChienLiu  About testing, I solved previous issue.And in the Retinanet folder, I find another test. But I met this issue.
Traceback (most recent call last):
  File "/home/zzz/RetinaNet/retinanet/test.py", line 56, in <module>
    main()
  File "/home/zzz/RetinaNet/retinanet/test.py", line 53, in main
    args.vis, args.ignore_cache, args.shuffle, config.TEST.HAS_RPN, config.dataset.proposal, args.thresh, logger=logger, output_path=final_output_path)
  File "/home/zzz/RetinaNet/retinanet/function/test_rcnn.py", line 54, in test_rcnn
    sym_instance.infer_shape(data_shape_dict)
  File "/home/zzz/RetinaNet/retinanet/../lib/utils/symbol.py", line 40, in infer_shape
    arg_shape, out_shape, aux_shape = self.sym.infer_shape(**data_shape_dict)
AttributeError: 'NoneType' object has no attribute 'infer_shape'
So far, I can't solve this issue.
About train, according to the author's readme,and erro message I training successful. You need to download dataset in the kitti website.

**Comment by wujiachen987** [comment]
I train the kitti,others are all right. However, the cls loss is increasing. And In my dataset, the same situation occurred.This is a training situation map.I don't know why, and how to solve it.Have you encountered such a situation during your training?Looking forward to your reply, Thanks.
@unsky 
![screenshot from 2017-12-24 13-20-49](https://user-images.githubusercontent.com/27916709/34324843-0211556e-e8bb-11e7-9779-0e76a2ee13d1.png)
