### ISSUE TITLE
您好，之前您训练好的模型不再匹配现在的网络了，有最新的.params和.states吗？

### ISSUE THREAD

**Issue by Jiaxinging** [unsky/RetinaNet#9]
可能是加了bn，所以您之前提供的模型参数导入会报错，请问有最新的模型文件可以分享一下吗？

**Comment by unsky** [comment]
是mxnet的版本问题

**Comment by Jiaxinging** [comment]
十分感谢您的回复！但是我用0.9.5跑模型会发现没有autogard报错，这个貌似是新版本mxnet才有的，所以请问现在的代码还是0.9.5吗？还有就是我导入您提供的.params文件，报错是bn_...  not initialized，我看代码是17年8月份加的bn，所以我以为是.params比较旧，不包含bn…我是一个自学目标检测做毕设的学生，不懂的比较多，打扰了…感谢您的开源！

**Comment by unsky** [comment]
1.0可以

**Comment by Jiaxinging** [comment]
换成1.0还是没有解决……错误如下，看起来是网络结构变化了……或者是层的名称有变化？
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    test.main()
  File "retinanet/test.py", line 50, in main
    args.vis, args.ignore_cache, args.shuffle, config.TEST.HAS_RPN, config.dataset.proposal, args.thresh, logger=logger, output_path=final_output_path)
  File "retinanet/function/test_rcnn.py", line 57, in test_rcnn
    sym_instance.check_parameter_shapes(arg_params, aux_params, data_shape_dict, is_train=False)
  File "retinanet/../lib/utils/symbol.py", line 49, in check_parameter_shapes
    assert k in arg_params, k + ' not initialized'
AssertionError: bn_data_gamma not initialized

**Comment by marshallixp** [comment]
用resnet_v2_50可以
